---
title: "sojourner package"
author: "Sheng Liu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{sojourner package}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r, eval=FALSE, echo=FALSE, warning=FALSE}
## load the library
library(sojourner)

## specify folder location
# example file with the pacakge
SWR1=system.file("extdata","SWR1",package="sojourner")
HTZ1=system.file("extdata","HTZ1",package="sojourner")

# local files
SWR1_2="/Volumes/wulab/Users/ranjana/Data/2015-11-09/SWR1_Halo"

# files on remoote dm11 server shared folder
SWR1_3="/groups/wu/wulab/Users/ranjana/Data/2015-11-09/SWR1_Halo"


## create master tracklist
comp=compareFolder(c(SWR1,HTZ1))


## compute MSD, CDF, dwellTime
msd(comp,dt=6,summarize=TRUE, plot=TRUE,output=FALSE)

displacementCDF(comp,dt=6)

dwellTime(comp,plot=TRUE,output=FALSE)


## use ?function for help
?msd
```
