#### plotLocalizations.Density.R
#### Wu Lab, Johns Hopkins University
#### Author: Xiaona Tang
#### Date: Dec 20, 2017

## plotLocalizations.Density-methods
##
###############################################################################
##' @name plotLocalizations.Density
##' @aliases plotLocalizations.Density
##' @title plotLocalizations.Density
##' @rdname plotLocalizations.Density-methods
##' @docType methods
##' @description Plot localization map of molecules from a list of files in a folder with color coded 
##'              by local density of each molecule. 
##'              
##' @usage
##'
##' plotLocalizations.Density(trackll=trackll,scale=256,r=125,bin=30,colors=c("blue4", "white", "red"),
##' AllDetection=TRUE,file.No=0,point.scale=0.15)
##'
##' @param trackll trajectory list generated by createTrackll() and processing. if NULL, user will be prompted to enter the trackll name.
##' @param scale The pixel scale of image data.
##' @param r Radius within each molecule to calculate density in nano meter (nm).
##' @param bin width of square-shape bins for calculating number of molecules in each bin.
##' @param colors choice of colors for density heat map, takes a vector of colors 
##' or a charactor string "Heat colors" for defaul heat colors from grDevices.
##' @param AllDetection A Logical indicator if plot each track as a molecule or plot each detection as a molecule.
##' @param file.No Select file(s) in the folder to plot. Default 0 for plotting all files in the folder.
##' @param point.scale Size of the dots representing the molecules.
##' @return
##' \itemize{
##' \item{PDF:} One PDF file with one plot on each page.
##' }
##' @details Plot localization map of molecules from a list of files in a folder with color coded 
##'              by local density of each molecule. The localization of molecule is considered as the first position of its track. 
##'              
##'          Upon running of the function, users will be prompted to input the name of the track list (trackll) if it's not specified.
##'          Input should be un-merged trackll.
##'          Two plots are generated for each image stack, one fills each square-shaped bin with heat color based on the number of 
##'          molecules within the bin.
##'          The other plot each molecule as a dot with user-specified gradient color based on local density of the molecule. 
##'          The local density of each molecule is calculated by counting the number of molecules within a given radius
##'          around the position of the molecule. The higher the number, the higher the local density.

##'
##' @examples
##'
##' # Generate trackll, and process, 
##' # e.g. mask region of interest, tracks from multiple files should not be merged.
##' folder=system.file("extdata","HSF",package="sojourner")
##' trackll=createTrackll(interact=F,folder,input=2, cores = 2)
##' trackll=maskTracks(folder,trackll)
##' 
##' # Plot localization map,
##' plotLocalizations.Density(trackll=trackll,scale=128,r=125,bin=30,colors=c("blue4", "white", "red"),
##' AllDetection=TRUE,file.No=0,point.scale=0.3)
##' # Plot only file No. 2 and increase the point size,
##' plotLocalizations.Density(trackll=trackll,scale=128,r=125,bin=30,colors=c("blue4", "white", "red"),
##' AllDetection=TRUE,file.No=2,point.scale=1)
##' 
##' @importFrom sampSurf spCircle
##' @export plotLocalizations.Density

#####################################################################################
#####################################################################################

plotLocalizations.Density<-function(trackll=trackll,scale=256, r=125, bin=30,colors=c("blue4", "white", "red"),AllDetection=TRUE,file.No=0, point.scale=0.15){
  
  ## Import trackll (un-merged) information  
  if (length(file.No)>1&min(file.No) == 0){
    stop("Wrong file.No input. Ceased.",call. = FALSE, domain = NULL)
  }
  
  if(is.null(trackll)){
    trackll.label<-readline(cat("Enter the un-merged trackll you want to plot:    "))
    trackll<-get(paste(trackll.label))
  }else{
    trackll<-trackll
    trackll.label<-stringr::str_extract(names(trackll),"[A-Z]+[a-z]+-+[A-Z]+[a-z]+-\\d")[1]
  }
  
  if (length(file.No)>=1&file.No[1]>0){
    trackll<-trackll[file.No]
  }
  else if (length(file.No)>1&min(file.No)==0){
    stop("Wrong file.No input. Ceased.",call. = FALSE, domain = NULL)
  }
  
  else if (length(file.No)>=1&file.No[1]>0){
    trackll<-trackll[file.No]
  }
  
  
  ## Output the plots into one PDF file in the working directory.
  pdf(paste("plotLocalization.Density.Heatmap-",trackll.label,"-",format(Sys.time(),"%Y%m%d.%H%M%S"),".pdf",sep=""),width=11.7,height=11.7)
  
  cat("\nPlotting...A PDF file will be output in the working directory.")
  
  ## Set plot area as black background and white frontground.
  oldpar <- par
  par(mar=c(3, 4, 4, 4),xpd=FALSE)
  
  par(mfrow=c(1,1),bg="black",fg="white")
  
  ## Get trackl info and plot localization map for each file in the trackll.
  for (i in c(1:length(trackll))){
    
    ## Get the localization of each track (molecule) as the first position of the track.
    localizations<-data.frame(matrix(ncol = 3, nrow = 0))
    if (AllDetection){
      for (j in c(1:length(trackll[[i]]))){
        localizations<-rbind(localizations,
                             data.frame(trackll[[i]][[j]]$x*resolution,trackll[[i]][[j]]$y*resolution,trackll[[i]][[j]]$Frame)
        )
      }
    }else{
      for (j in c(1:length(trackll[[i]]))){
        localizations<-rbind(localizations,
                             data.frame(trackll[[i]][[j]]$x[1]*resolution,trackll[[i]][[j]]$y[1]*resolution,trackll[[i]][[j]]$Frame[1])
        )
      }
    }
    
    names(localizations)<- c("x", "y","Frame")
    
    ## Calculate local molecule density by counting the molecule number within a given radius.
    sp::coordinates(localizations) <- c("x", "y")
    for (k in c(1:length(localizations$x))){
      ## Generate a named vector "cp" to make this loop work in both Mac and PC version of R.
      cp=c(localizations[k,]$x,localizations[k,]$y)
      names(cp)=c("x","y")
      sp.n = sampSurf::spCircle(r/1000, centerPoint=cp, spID='tree.1') 
      count.n <- sp::over(localizations, sp.n$spCircle)
      localizations$density[k]=sum(count.n,na.rm = T)
    }
    
    ## Determine which bin each localization is in.
    v = sp::GridTopology(c(0,0), c(bin/1000,bin/1000), 
                         c(ceiling(scale*resolution*1000/bin)+1,ceiling(scale*resolution*1000/bin)+1))
    w = sp::SpatialGrid(grid = v)
    localizations.bin <- sp::over(localizations, w)
    localizations$bin <- unlist(localizations.bin)
    coords<-sp::coordinates(w)
    for (g in c(1:nrow(localizations))){
      localizations$bin.xc[g]<-coords[[localizations$bin[g],1]]
      localizations$bin.yc[g]<-coords[[localizations$bin[g],2]]
    }
    ## Calculate molecule/localization density in each bin.
    bin.density<-split(localizations , f=localizations$bin)
    for (l in c(1:length(bin.density))){
      names(bin.density)[l]<-length(bin.density[[l]])
    }
    bin.density<-bin.density[which(as.numeric(names(bin.density))>0)]
    #print(max(as.numeric(names(bin.density))))
    #print(length(bin.density))
    #print(sum(as.numeric(names(bin.density))))
    
    
    #########plot binned super-resolution image in heat color.
    cl=grDevices::heat.colors(max(as.numeric(names(bin.density))))
    
    par(mar=c(3, 4, 4, 4),xpd=FALSE)
    par(mfrow=c(1,1),bg="black",fg="white")
    plot.new()
    
    plot.window(xlim=c(0,scale*resolution),ylim=c(0,scale*resolution),xaxs = "i", yaxs = "i")
    axis(1,cex.axis=1,col.axis="white",at=seq(0,scale*resolution,by=2))
    axis(2,cex.axis=1,col.axis="white",at=seq(0,scale*resolution,by=2))
    if(file.No==0){
      mtext(paste("Image No.",i,"  ",gsub(".mat","",names(trackll[i]))),side=3,line=0.5,cex=1.2,col.main="white")            
    }
    else{
      mtext(paste("Image No.",file.No,"  ",gsub(".mat","",names(trackll[i]))),side=3,line=0.5,cex=1.2,col.main="white")            
    }
    mtext(expression(paste("X (",mu,"m)")),side=1,line=2,cex.lab=1,col="white")
    mtext(expression(paste("Y (",mu,"m)")),side=2,line=2,cex.lab=1,col="white")
    
    box()
    
    for(o in c(1:length(bin.density))){
      rect((bin.density[[o]]$bin.xc[1]-bin/2000), 
           (bin.density[[o]]$bin.yc[1]-bin/2000), 
           (bin.density[[o]]$bin.xc[1]+bin/2000), 
           (bin.density[[o]]$bin.yc[1]+bin/2000), density = NULL, angle = 45,
           col = cl[as.numeric(names(bin.density)[[o]])], border=NA)
    }
    legend.col(col = cl, lev = as.numeric(names(bin.density)))
    ## Add bin size and molecule number (n) as text legend to the topright corner of each plot.
    legend("topright",paste(rep(c("bin = ","n = ")), rep(c(bin,nrow(localizations))),rep(c(" nm",""))),col="white",bty = "n")
    
    
    ## Generate color gradient/ramp based on the highest molecule density in each file.
    if(length(colors)==1){
      if(colors=="Heat colors"){
        cl=grDevices::heat.colors(max(localizations$density))
      }else{
        cat("\nPlease re-specify colors\n")
      }
      
    }else{
      cl <- colorRampPalette(colors)(n = max(localizations$density))
    }
    
    #cl=colorspace::diverge_hsv(max(localizations$density))
    #cl=colorspace::diverge_hcl(max(localizations$density))
    #cl <- colorRampPalette(c("blue4", "white", "red"))(n = max(localizations$density))
    
    ## plot the molecules as dots color coded by it's local density.
    plot.new()
    plot.window(xlim=c(0,scale*0.107),ylim=c(0,scale*0.107),xaxs = "i", yaxs = "i")
    
    axis(1,cex.axis=1,col.axis="white",at=seq(0,scale*resolution,by=2))
    axis(2,cex.axis=1,col.axis="white",at=seq(0,scale*resolution,by=2))
    mtext(gsub(".mat","",names(trackll[i])),side=3,line=0.5,cex=2,col.main="white")             
    mtext(expression(paste("X (",mu,"m)")),side=1,line=2,cex.lab=1,col="white")
    mtext(expression(paste("Y (",mu,"m)")),side=2,line=2,cex.lab=1,col="white")
    box()
    
    for(i in c(1:length(localizations$x))){
      points(localizations[i,]$x,localizations[i,]$y,pch=16,col=cl[localizations[i,]$density],cex=point.scale)
    }
    ## Add color gradient legend to the right edge of each plot.
    .legend.col(col = cl, lev = localizations$density)
    ## Add radius and molecule number (n) as text legend to the topright corner of each plot.
    legend("topright",paste(rep(c("r = ","n = ")), rep(c(r,nrow(localizations))),rep(c(" nm",""))),col="white",bty = "n")
    
  }
  
  ## Reset plotting area parameters.
  par(oldpar)
  par(mfrow=c(1,1),bg="white",fg="black")
  dev.off()
  cat("\nDone!\n\n")
}

