#### plotIndividualTracks.R
#### Wu Lab, Johns Hopkins University
#### Author: Xiaona Tang
#### Date: Aug 15, 2018

## plotIndividualTracks-methods
##
###############################################################################
##' @name plotTrackOverlay.Dcoef
##' @aliases plotIndividualTracks
##' @title plotIndividualTracks
##' @rdname plotTrackOverlay.Dcoef-methods
##' @docType methods
##' @description Plot individual tracks one by one, with grid layout.
##'              Tracks are sorted by their lengths.
##'              
##' @usage
##'
##' plotIndividualTracks<-function(trackll=trackll,grid.size=c(1000,1000),resolution=0.107,t.interval=0.5)
##'
##' @param trackll trajectory list generated by createTrackll() and processing. 
##' @param grid.size The size of each plot grid in nanometers. Default 1000 nm for x and y axis, respectively.
##' @param resolution ratio of pixel to µM.
##' @param t.interval Time interval for image aquisition. Default 0.5 sec (500ms).
##' 
##' @return
##' \itemize{
##' \item{PDF:} One PDF file with 120 tracks on each page.
##' }
##' @details Plot individual track/trajectory one by one, and the tracks will be layout in 15X8 grids.
##'              
##'          Upon running of the function, users will be prompted to input the name of the track list (trackll).
##'          Input un-merged trackll and the plotting will start. 
##'          The Dcoef is calculated by "static" method, which stabilizes the number of time lags used for fitting using time lag 2~ 5 despite the total time lags measured.

##'
##' @examples
##'
##' # Generate trackll, and process, 
##' # e.g. mask region of interest, tracks from multiple files should not be merged.
##' folder=system.file("extdata","HSF",package="sojourner")
##' trackll=createTrackll(interact=F,folder,input=2, cores = 2)
##' trackll=maskTracks(folder,trackll)
##' trackll=mergeTracks(folder, trackll)
##' 
##' # Plot individual tracks,
##' plotIndividualTracks<-function(trackll=trackll,grid.size=c(1000,1000),resolution=0.107,t.interval=0.5)

##' @export plotIndividualTracks

#####################################################################################
#####################################################################################



## Function for plotting individual tracks one by one, with grid layout (120 tracks/page).
## Sorted with track length.

plotIndividualTracks<-function(trackll=trackll,grid.size=c(1000,1000),resolution=0.107,t.interval=0.5){

#library(lattice)
#library(grid)    
    
trackll<-trackll[[1]]

traj.df<-setNames(data.frame(matrix(ncol = 5, nrow = 0)), c("x", "y", "z","Frame","trajNo"))
for(i in c(1:length(trackll))){
  traj.n<-trackll[[i]][,c("x","y","z")]
  traj.n$x<-(traj.n$x-min(traj.n$x))*resolution*1000
  traj.n$y<-(traj.n$y-min(traj.n$y))*resolution*1000
  f.n<-rep(i,length(traj.n$x))
  l.n<-rep(length(traj.n$x),length(traj.n$x))
  traj.n$trajNo<-unlist(f.n)
  traj.n$trajLength<-unlist(l.n)
  traj.df<-rbind(traj.df,traj.n)
}
traj.df<-traj.df[order(traj.df$trajLength,decreasing=TRUE),]
new.trajSeq<-sort(table(traj.df$trajNo),decreasing = TRUE)
new.trajNo<-c()
for(i in c(1:length(new.trajSeq))){
  f.n<-rep(i,new.trajSeq[[i]])
  new.trajNo<-append(new.trajNo,f.n)
}
traj.df$new.trajNo<-unlist(new.trajNo)
traj.df<-transform(traj.df,new.trajNo=factor(new.trajNo))

dwellTimes<-c()
for(i in c(1:length(trackll))){
    dwellTimes=append(dwellTimes,paste(new.trajSeq[[i]]*t.interval,"s",sep=""))
}

######################### Using the grid library to add text to each panel #####################

pdf(paste("plotIndividualTraj-",names(trackll),"-",format(Sys.time(),"%Y%m%d.%H%M%S"),".pdf",sep=""),width=11.7,height=8.3)


trajplot<-lattice::xyplot(traj.df$y~traj.df$x|traj.df$new.trajNo,type="l",col="red",
                 xlab="x displacement (nm)",ylab="y displacement (nm)",
                 xlim=c(1,grid.size[1]),ylim=c(1,grid.size[2]),
                 main=paste(names(trackll), "   n=",length(trackll)),
                 panel=function(x, y, ...) {
                   panel.xyplot(x, y, ...);
                   grid::grid.text(dwellTimes[panel.number()],just = "right",unit(0.98, 'npc'), 
                             unit(0.9, 'npc'),gp=gpar(col="blue",fontface = "bold"))
                 },
                 layout=c(15,8),as.table=TRUE
)

print(trajplot)

dev.off()

cat("The plot has been saved as a PDF in the working directory.")
}


