#### plotIndividualTracks.R
#### Wu Lab, Johns Hopkins University
#### Author: Xiaona Tang
#### Date: Aug 15, 2018

## plotIndividualTracks-methods
##
###############################################################################
##' @name plotIndividualTracks
##' @aliases plotIndividualTracks
##' @title plotIndividualTracks
##' @rdname plotIndividualTracks-methods
##' @docType methods
##' @description Plot individual tracks one by one, with grid layout.
##'              Tracks can be sorted by their lengths or diffusion coefficients.
##'              
##' @usage
##'
##' plotIndividualTracks(trackll=trackll,grid.size=c(1000,1000),resolution=0.107,t.interval=0.5,sort="RT",legend="Both",lag=c(2:5),dt=6)
##'
##' @param trackll trajectory list generated by createTrackll() and processing. 
##' @param grid.size The size of each plot grid in nanometers. Default 1000 nm for x and y axis, respectively.
##' @param resolution ratio of pixel to µM.
##' @param t.interval Time interval for image aquisition. Default 0.5 sec (500ms).
##' @param sort trajectories will be sorted by given parameters, "RT" for dwell time, "Dcoef" for diffusion coefficient, "Rsqare" for R squared of Mean squared Displacement (MSD) fitting.
##' @param legend values to be plot as legend on the topright corner of each grid/panel, "RT" for dwell time, "Dcoef" for diffusion coefficient, 
##' "Both" for both dwell time and diffusion coefficient, "None" for not plotting legend.
##' @param lag time intervals for linear regression to calculate diffusion coefficient, default is 2 to 5.
##' @param dt max time interval, default is 6.
##' 
##' @return
##' \itemize{
##' \item{PDF:} One PDF file with 120 tracks on each page.
##' }
##' @details Plot individual track/trajectory one by one, and the tracks will be layout in 15X8 grids. 
##' The title of each grid indicates the sequence of the track in the original trackll.
##'              
##'
##' @examples
##'
##' # Generate trackll, and process, 
##' # e.g. mask region of interest, tracks from multiple files should not be merged.
##' folder=system.file("extdata","HSF",package="sojourner")
##' trackll=createTrackll(interact=F,folder,input=2, cores = 2)
##' trackll=maskTracks(folder,trackll)
##' trackll=mergeTracks(folder, trackll)
##' trackll=filterTrack(trackll,filter=c(7,Inf))
##' 
##' # Plot individual tracks,
##' plotIndividualTracks(trackll,grid.size=c(1000,1000),resolution=0.107,t.interval=0.5,sort="RT",legend="Both",lag=c(2:5),dt=6)

##' @export plotIndividualTracks

#####################################################################################
#####################################################################################



## Function for plotting individual tracks one by one, with grid layout (120 tracks/page).
## Sorted with track length.

plotIndividualTracks<-function(trackll=trackll,grid.size=c(1000,1000),resolution=0.107,t.interval=0.5,sort=c("RT","Dcoef","Rsquare"),legend=c("RT","Dcoef","Both","None"),lag=c(2:5),dt=6){

#library(lattice)
#library(grid)    
  if(sort=="Dcoef"|legend=="Dcoef"|legend=="Both"){
    trackll<-filterTrack(trackll,filter=c(min=dt+1,max=Inf))
  }    

# combine all track coordinates into one data frame
traj.df<-setNames(data.frame(matrix(ncol = 6, nrow = 0)), c("x", "y", "z","Frame","trajNo","trajID"))
for(i in seq_along(trackll[[1]])){
  traj.n<-trackll[[1]][[i]][,c("x","y","z","Frame")]
  traj.n$x<-(traj.n$x-min(traj.n$x))*resolution*1000
  traj.n$y<-(traj.n$y-min(traj.n$y))*resolution*1000
  f.n<-rep(i,length(traj.n$x))
  l.n<-rep(length(traj.n$x),length(traj.n$x))
  ID.n<-rep(names(trackll[[1]][i]),length(traj.n$x))
  traj.n$trajNo<-unlist(f.n)
  traj.n$trajLength<-unlist(l.n)
  traj.n$trajID<-unlist(ID.n)
  traj.df<-rbind(traj.df,traj.n)
}

# Add Dcoef values to the data frame
if(sort=="Dcoef"|sort=="Rsquare"|legend=="Dcoef"|legend=="Both"){
  msd.track=function(track,dt=6,resolution=0.107,at.dt=F){
    
    if (at.dt == F){
      
      # calculate msd for track at 1~dt
      msd_track=c()
      for (i in 1:dt){
        
        # caculate msd for track at specified dt
        track.sqd=squareDisp(track,dt=i,resolution=resolution)
        # extract square.disp into a vector
        square.disp=do.call(rbind,track.sqd)$square.disp
        # remove NA and get the genuine mean
        msd_track[i]=mean(square.disp,na.rm=T)
      }
      
    }else{
      
      # caculate msd for track at specified dt
      track.sqd=squareDisp(track,dt=dt,resolution=resolution)
      # extract square.disp into a vector
      square.disp=do.call(rbind,track.sqd)$square.disp
      # remove NA and get the genuine mean
      msd_track=mean(square.disp,na.rm=T)
    }
    
    return(msd_track)
  }
  Dcoef.linear=c()
  Dcoef=c()
  R.squared=c()
  x=lag*t.interval
  dimension=2
  for (j in seq_along(trackll[[1]])){
    msd.n=msd.track(trackll[[1]][[j]], resolution=resolution,dt=dt, at.dt=F)
    fit=lm(msd.n[lag]~x)
    MSDslope=coefficients(fit)[2]/(2*dimension)
    Dcoef.linear=append(Dcoef.linear,rep(MSDslope,dim(trackll[[1]][[j]])[1]))
    Log.D.coef=log(MSDslope)
    Log.D.coef=formatC(Log.D.coef,digits=2, format="f") 
    Dcoef=append(Dcoef,rep(Log.D.coef,dim(trackll[[1]][[j]])[1]))
    R.squared=append(R.squared,rep(summary(fit)$r.squared,dim(trackll[[1]][[j]])[1]))
  }
  traj.df$Dcoef.linear<-unlist(Dcoef.linear)
  traj.df$Dcoef<-unlist(Dcoef)
  traj.df$R.squared<-unlist(R.squared)
}

# Sort tracks by dwell time or diffusion coefficient
if(sort=="RT"){
  traj.df<-traj.df[order(traj.df$trajLength,decreasing=TRUE),]
  
  # Generate new track sequence after sorting
  new.trajSeq<-sort(table(traj.df$trajNo),decreasing = TRUE)
  new.trajNo<-c()
  for(i in seq_along(new.trajSeq)){
    f.n<-rep(i,new.trajSeq[[i]])
    new.trajNo<-append(new.trajNo,f.n)
  }
  traj.df$new.trajNo<-unlist(new.trajNo)
  new.trajSeq<-unique(traj.df$trajNo)
  
}else if(sort=="Dcoef"){
  traj.df<-traj.df[order(traj.df$Dcoef.linear,decreasing=TRUE),]
  
  # Generate new track sequence after sorting
  new.trajSeq<-unique(traj.df$trajNo)
  new.trajNo<-c()
  for(i in seq_along(new.trajSeq)){
    f.n<-rep(i,length(traj.df$trajNo[which(traj.df$trajNo==new.trajSeq[i])]))
    new.trajNo<-append(new.trajNo,f.n)
  }
  traj.df$new.trajNo<-unlist(new.trajNo)
}else if(sort=="Rsquare"){
  traj.df<-traj.df[order(traj.df$R.squared,decreasing=TRUE),]
  
  # Generate new track sequence after sorting
  new.trajSeq<-unique(traj.df$trajNo)
  new.trajNo<-c()
  for(i in seq_along(new.trajSeq)){
    f.n<-rep(i,length(traj.df$trajNo[which(traj.df$trajNo==new.trajSeq[i])]))
    new.trajNo<-append(new.trajNo,f.n)
  }
  traj.df$new.trajNo<-unlist(new.trajNo)
}


# Add levels to the data frame by new track sequence
traj.df<-transform(traj.df,new.trajNo=factor(new.trajNo))

# generate dwell time values and Dcoef values for plotting as legend
dwellTimes<-c()
for(i in seq_along(trackll[[1]])){
  frames=max(traj.df$Frame[which(traj.df$new.trajNo==i)])-min(traj.df$Frame[which(traj.df$new.trajNo==i)])+1
  dwellTimes=append(dwellTimes,paste("t=",frames*t.interval,"s",sep=""))
}
if(sort=="Dcoef"|legend=="Dcoef"|legend=="Both"){
  uniqueDcoef=c()
  uniqueRsquared=c()
  for (k in seq_along(trackll[[1]])){
    uniqueDcoef.k=formatC(traj.df$Dcoef.linear[which(traj.df$new.trajNo==k)][1],digits=4, format="f")
    uniqueDcoef=append(uniqueDcoef,as.expression(bquote(D[coef]~"="~.(uniqueDcoef.k))))
    #uniqueRsquared.k=paste("R squared=",formatC(traj.df$R.squared[which(traj.df$new.trajNo==k)][1],digits=2, format="f"))
    #uniqueRsquared.k=formatC(traj.df$R.squared[which(traj.df$new.trajNo==k)][1],digits=2, format="f")
    R2=as.numeric(formatC(traj.df$R.squared[which(traj.df$new.trajNo==k)][1],digits=2, format="f"))
    uniqueRsquared.k= as.expression(bquote(R^2~"="~.(R2)))
    uniqueRsquared=append(uniqueRsquared,uniqueRsquared.k)
  }
  
}

######################### Using the grid library to add text to each panel #####################

pdf(paste("plotIndividualTraj-",names(trackll),"-",format(Sys.time(),"%Y%m%d.%H%M%S"),".pdf",sep=""),width=11.7,height=8.3)

if (legend=="RT"){
  trajplot<-lattice::xyplot(traj.df$y~traj.df$x|traj.df$new.trajNo,type="l",col="red",
                            xlab="x displacement (nm)",ylab="y displacement (nm)",
                            xlim=c(-100,grid.size[1]),ylim=c(-100,grid.size[2]),
                            main=paste(names(trackll), "   n=",length(trackll[[1]]),"   sorted by ",sort),
                            #par.settings = list(layout.heights = list(strip = 2)), 
                            par.strip.text = list(col = "black",cex=1),
                            strip=lattice::strip.custom(factor.levels=as.character(new.trajSeq)),
                            
                            panel=function(x, y, ...) {
                              lattice::panel.xyplot(x, y, ...);
                              grid::grid.text(dwellTimes[lattice::panel.number()],just = "right", grid::unit(0.98, 'npc'), 
                                              grid::unit(0.9, 'npc'),gp=grid::gpar(col="blue",fontface = "bold"))
                            },
                            
                            layout=c(15,8),as.table=TRUE
  )
}else if(legend=="Dcoef"){
  trajplot<-lattice::xyplot(traj.df$y~traj.df$x|traj.df$new.trajNo,type="l",col="red",
                            xlab="x displacement (nm)",ylab="y displacement (nm)",
                            xlim=c(-100,grid.size[1]),ylim=c(-100,grid.size[2]),
                            main=paste(names(trackll), "   n=",length(trackll[[1]]),"   sorted by ",sort),
                            #par.settings = list(layout.heights = list(strip = 2)), 
                            par.strip.text = list(col = "black",cex=1),
                            strip=lattice::strip.custom(factor.levels=as.character(new.trajSeq)),
                            
                            panel=function(x, y, ...) {
                              lattice::panel.xyplot(x, y, ...);
                              grid::grid.text(uniqueDcoef[lattice::panel.number()],just = "right", grid::unit(0.98, 'npc'), 
                                              grid::unit(0.9, 'npc'),gp=grid::gpar(col="blue",cex=0.6));
                              grid::grid.text(uniqueRsquared[lattice::panel.number()],just = "right", grid::unit(0.98, 'npc'), 
                                              grid::unit(0.6, 'npc'),gp=grid::gpar(col="blue",cex=0.6))
                            },
                            
                            layout=c(15,8),as.table=TRUE
  )
}else if(legend=="Both"){
  trajplot<-lattice::xyplot(traj.df$y~traj.df$x|traj.df$new.trajNo,type="l",col="red",
                            xlab="x displacement (nm)",ylab="y displacement (nm)",
                            xlim=c(-100,grid.size[1]),ylim=c(-100,grid.size[2]),
                            main=paste(names(trackll), "   n=",length(trackll[[1]]),"   sorted by ",sort),
                            #par.settings = list(layout.heights = list(strip = 2)), 
                            par.strip.text = list(col = "black",cex=1),
                            strip=lattice::strip.custom(factor.levels=as.character(new.trajSeq)),
                            
                            panel=function(x, y, ...) {
                              lattice::panel.xyplot(x, y, ...);
                              grid::grid.text(dwellTimes[lattice::panel.number()],just = "right", grid::unit(0.98, 'npc'), 
                                              grid::unit(0.9, 'npc'),gp=grid::gpar(col="blue",cex=0.6));
                              grid::grid.text(uniqueDcoef[lattice::panel.number()],just = "right", grid::unit(0.98, 'npc'), 
                                              grid::unit(0.75, 'npc'),gp=grid::gpar(col="blue",cex=0.6));
                              grid::grid.text(uniqueRsquared[lattice::panel.number()],just = "right", grid::unit(0.98, 'npc'), 
                                              grid::unit(0.6, 'npc'),gp=grid::gpar(col="blue",cex=0.6))
                            },
                            
                            layout=c(15,8),as.table=TRUE
  )
}else{
  trajplot<-lattice::xyplot(traj.df$y~traj.df$x|traj.df$new.trajNo,type="l",col="red",
                            xlab="x displacement (nm)",ylab="y displacement (nm)",
                            xlim=c(-100,grid.size[1]),ylim=c(-100,grid.size[2]),
                            main=paste(names(trackll), "   n=",length(trackll[[1]]),"   sorted by ",sort),
                            #par.settings = list(layout.heights = list(strip = 2)), 
                            par.strip.text = list(col = "black",cex=1),
                            strip=lattice::strip.custom(factor.levels=as.character(new.trajSeq)),
                            layout=c(15,8),as.table=TRUE
  )
}


print(trajplot)

dev.off()

cat("\nThe plot has been saved as a PDF in the working directory.")
}


